# Generated by Django 4.1.1 on 2022-10-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collaboration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("JobRol", models.CharField(max_length=20)),
                ("development", models.BooleanField()),
                ("design", models.BooleanField()),
                ("business", models.BooleanField()),
            ],
        ),
        migrations.RemoveField(model_name="donation", name="JobRol",),
        migrations.RemoveField(model_name="donation", name="business",),
        migrations.RemoveField(model_name="donation", name="collaboration",),
        migrations.RemoveField(model_name="donation", name="design",),
        migrations.RemoveField(model_name="donation", name="development",),
    ]
