# Generated by Django 4.1.1 on 2022-10-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0002_collaboration_job_remove_donation_jobrol_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="job", old_name="JobRol", new_name="jobrol",),
    ]
