# Generated by Django 4.1.1 on 2022-10-02 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0007_alter_collaboration_createdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaboration",
            name="createdate",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 2, 18, 28, 35, 987494)
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="createdate",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 2, 18, 28, 35, 986889)
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="createdate",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 2, 18, 28, 35, 988226)
            ),
        ),
    ]
