# Generated by Django 4.1.1 on 2022-10-02 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0008_alter_collaboration_createdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaboration",
            name="createdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 2, 18, 33, 20, 561063)
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="createdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 2, 18, 33, 20, 560699)
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="createdate",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 2, 18, 33, 20, 561477)
            ),
        ),
    ]
